### ISSUE TITLE
Ontologies Implementation Possibilities

### ISSUE THREAD

**Issue by Xhark-Blues** [repositive/muninn#15]
WE need to find a way to implement the ontologies at least until the point of being able to search for a term into it a get the related terms.  
Candidates so far:
 - [Neo4j](https://neo4j.com/): Graph database
 - [OLS](http://www.ebi.ac.uk/ols/index): Ontologye Lookup Service
    - [~~docker~~](https://github.com/MaastrichtUniversity/ols-docker) 
    - [API](http://www.ebi.ac.uk/ols/docs/api)
-  Node libraries: Javascript implementation of the graph:
    - [rdflib](https://github.com/linkeddata/rdflib.js)
    - [rdfstore](https://www.npmjs.com/package/rdfstore)

**Comment by Istar-Eldritch** [comment]
Can you describe potential implementations?

**Comment by Xhark-Blues** [comment]
The OLS docker got discarded:
       - Highly inefficient. It contains to many things and basically all the ontologies they have. 
       - Hard to configure locally to use our own owl files.

Starting with the OSL API:
- Search for a term in an specific ontology. It checks over term labels, synonyms, descriptions, identifiers and annotation properties. Its configurable:
```bash
curl 'http://www.ebi.ac.uk/ols/api/search?q={cancer}&ontology={efo}' -i -H 'Accept: application/json'
```
- With the iri(with double encoding), we could get terms related it it. Such us children:
```bash
curl 'http://www.ebi.ac.uk/ols/api/ontologies/efo/terms/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0000311/children' -i -H 'Accept: application/json'
```

**Comment by Istar-Eldritch** [comment]
Closing as this was implemented in [metis](https://github.com/repositive/metis)

@DrWilliamsSteven you may find the research @Xhark-Blues did on the OSL API useful and it may even compliment zooma.

Feel free to reopen or add more comments if required.
