### ISSUE TITLE
Huggin requirements

### ISSUE THREAD

**Issue by Xhark-Blues** [repositive/muninn#18]
Huginn
---

## Requirements

Get the proper list of possible autocompleted words for a query base on the following *****inputs**:
- Current state of the query: **Tree**. 
- Actual results from the query as it is with out the term to autocomplete for: **List of controlled voabulary**.
- Text wroten so far: **Prefix**

## Internals

1- Get the posible complete words from Muninn.
2.1- Transform the current state of the query to another one without the node to autocomplete in. That would be done depending on the operation in which the term is involve in.
  - **AND**: Delete node and place sibling in the position of the operator.
  - **OR**: Delete node and swap or to not sibling, so it get everithing but the things alreade there
  - **NOR**: Delete node

2.2- Add all the aotocomplition from Muninn as OR 
3- Run the new query through [---] to get the parcial results agregations by term.
4- Return agreagations

**Comment by Istar-Eldritch** [comment]
Closing as complete, feel free to rectify this action if it's not valid.
